all:
	g++ main.cpp csketch.hpp csketch_merged.hpp hasher.hpp hasher_merged.hpp -O3 -o singletables -fopenmp -std=c++11
	g++ main_batch.cpp csketch.hpp csketch_merged.hpp hasher.hpp hasher_merged.hpp -O3 -o singletables_batch -fopenmp -std=c++11

#./pis 23 20 0.01 0.002 8 2
